const ACTION_TYPES = {

  //product related with stores
  ADD_TO_CART: 'ADD_TO_CART',
  ADD_QUANTITY_TO_CART: 'ADD_QUANTITY_TO_CART',
  REMOVE_ITEM_CART: 'REMOVE_ITEM_CART',
  REMOVE_TO_CART: 'REMOVE_TO_CART',
  //Store related with tax
  ADD_STORE: 'ADD_STORE',
  REMOVE_STORE: 'REMOVE_STORE',
  //User Related
  SIGN_UP_USER: 'SIGN_UP_USER',
  REMOVE_SIGN_UP_USER: 'REMOVE_SIGN_UP_USER',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOCATION: 'USER_LOCATION',
  //FAV PRODUCTS
  ADD_FAV: 'ADD_FAV',
  DELETE_FAV: 'DELETE_FAV',
  GET_FAV: 'GET_FAV'
};

export { ACTION_TYPES };
